output   = "models"
wipe     = true
no-tests = false
add-enum-types = true

[psql]
  dbname = "go_template"
  host   = "localhost"
  port   = 5432
  sslmode = "disable"
  user   = "go_template_role"
  pass   = "wednesday123456"