// Code generated by SQLBoiler 4.12.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	GorpMigrations string
	Notes          string
	Roles          string
	Users          string
}{
	GorpMigrations: "gorp_migrations",
	Notes:          "notes",
	Roles:          "roles",
	Users:          "users",
}
